Add file validation
askap-vast/vast-tools pull request #370
Opened 2022-04-04 12:38 UTC by ddobie

Fix #369.

2022-04-05 03:20 UTC, pep8speaks commented
Hello @ddobie! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`tests/test_query.py`](https://github.com/askap-vast/vast-tools/blob/ba0311acc25aa6e132ea20b1bd1f403eed003e32/tests/test_query.py):

> [Line 803:1](https://github.com/askap-vast/vast-tools/blob/ba0311acc25aa6e132ea20b1bd1f403eed003e32/tests/test_query.py#L803): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2023-01-18 06:12 UTC, ddobie commented
Not sure why @pep8speaks hasn't updated its comment, but running pycodestyle on my own machine shows that the code is PEP8 compliant.

2023-01-18 20:23 UTC, ajstewart reviewed
Looks like a good change - I ran into this exact problem when trying to test the `find_fields` function locally!

Only a couple of comments on the test and the error level.

2023-01-18 20:23 UTC, ajstewart commented on vasttools/query.py
> +            )
I don't see this as a `critical` error - that usually denotes something that will cause the task to completely crash out. Given that the idea is that this picks out the missing ones and allows the query to continue it should probably be at the `warning` level?
```suggestion
            self.logger.warning(
                "Not all requested data is available! See above for details."
            )
            self.logger.warning(
                "Query will continue run, but proceed with caution."
            )
```

2023-01-18 20:23 UTC, ajstewart commented on tests/test_query.py
> +        assert all_available == query._check_data_availability()
Can a test cover the `False` return case as well?

2023-01-19 00:04 UTC, ddobie commented on tests/test_query.py
> +        assert all_available == query._check_data_availability()
It does, doesn't it?

It's parametrised to cover a variety of scenarios

2023-01-19 07:47 UTC, ajstewart commented on tests/test_query.py
> +        assert all_available == query._check_data_availability()
Apologies I managed to completely miss that!

2023-01-19 07:47 UTC, ajstewart approved these changes

2023-01-19 07:48 UTC, ajstewart requested changes
Actually just realised - change log. Does any doc also need to be updated to state this behaviour?

2023-01-20 04:23 UTC, ddobie commented
Good catch. Have updated.

2023-01-20 07:11 UTC, ajstewart approved these changes
Looks good to me!

2023-01-22 21:39 UTC, merged