Enable full survey access
askap-vast/vast-tools pull request #408
Opened 2023-03-23 02:51 UTC by ddobie

2023-04-16 23:16 UTC, ddobie commented
@ajstewart this is a big one, but it needed to be because of all the changes in the full survey data specs.

Specifically,
1. We no longer use "epochs". The terminology is retained in all VAST software to save the hassle of changing everything, but they're more like groups than epochs. Specifically, each epoch no longer necessarily contains all fields, and each field can be observed multiple times in one epoch. The reason for this is that the pilot observations were scheduled such that VAST monopolised the telescope for as long as required to observe all fields, which is extremely inefficient and therefore not feasible for the full surveys. Instead, we're planning on redefining epochs to be all observations on a given day (or maybe week).
2. The field names no longer have an "A" on the end, which was a leftover from when observations were potentially going to be interleaved. Allowing access to data that uses both naming schemes is not trivial, but we can now handle it.

2023-04-19 22:35 UTC, ajstewart requested changes
Some comments and suggestions on a first pass through. Don't envy dealing with that field name change!

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +                                )
```suggestion
                rms_file = rms_file.with_suffix('.restored.conv')
```
Is `rms_file` already a Path here? If so you could do the suggestion.

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
>                  prev_num
As changing anyway consider updating to modern string formatting method.

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +        self.logger.debug(row)
Log message has no context to help identify it.

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +                row['name']
```suggestion
                f"Source '{row['name']}' not in the requested epoch footprint."
```

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +                epoch_fields_names = epoch_fields_names.str.rstrip('A')
Can replace with the function you defined in survey was it? Might be useful in utils if it's also used here.

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +            return [np.nan] * 7
Why is it 7 NaNs here and elsewhere?

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +                    "requested survey footprint", sum(mask)
```suggestion
                    f"Removing {sum(mask)} sources outside the requested survey footprint"
```

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +    def _check_survey(self, epochs: list):
```suggestion
    def _check_survey(self, epochs: list) -> None:
```

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +        self.logger.debug(f"self.vast_full: {self.vast_full}")
This function seems pretty important to test?

2023-04-19 22:35 UTC, ajstewart commented on tests/test_query.py
> +                                         mocker) -> None:
I'm not suggesting to fix this everywhere, but the type hint for the mocker can be declared as so: https://pytest-mock.readthedocs.io/en/latest/remarks.html#type-annotations

2023-04-19 22:35 UTC, ajstewart commented on vasttools/query.py
> +                        field_centre_names == f.rstrip('A')
The strip here, what's the reason that `available_fields` can't be sorted before this point?

2023-04-19 22:38 UTC, ajstewart commented on vasttools/query.py
> +            return [np.nan] * 7
Ah it's number of columns isn't it?

2023-04-19 23:22 UTC, ddobie commented on vasttools/query.py
> +                                )
The problem with that is that the `.restored.conv` is in the middle of the file name, not the suffix

2023-04-19 23:22 UTC, ddobie commented on vasttools/query.py
> +                                )
And as far as I can tell, there's no nice way to do a simple replace on a Path

2023-04-19 23:33 UTC, ddobie commented on vasttools/data/csvs/low_field_centres.csv
> +VAST_0056-31A,14.12074696385262,-31.397409554915622
It's easier to remove the A when it's not needed than it is to add the A when it is needed

2023-04-19 23:36 UTC, ddobie commented on vasttools/query.py
> +                        field_centre_names == f.rstrip('A')
I suspect this strip might actually be superfluous now that I'm looking at it closer. `available_fields` is built from `the_fields` which has already been stripped.

2023-04-20 08:06 UTC, ajstewart commented on vasttools/query.py
> +                                )
Ah of course!

2023-05-11 10:28 UTC, ddobie commented on vasttools/query.py
> +                        field_centre_names == f.rstrip('A')
Available fields isn't always stripped, but is matched against a list of stripped fields. Stripping as needed vs doing it all at once should be equally fast.

2023-05-11 11:53 UTC, ajstewart approved these changes
Thanks for adding the tests.

If you're satisfied it's all working then it looks good to me!

2023-05-16 04:15 UTC, merged